### ISSUE TITLE
Question about Hard-coded Resource Information

### ISSUE THREAD

**Issue by RipperJ** [Licheng-Guo/AutoBridge#13]
Hello, I'm wondering how to get the drop of resource after DDR is enabled. I found in [src/formator.py](https://github.com/Licheng-Guo/AutoBridge/blob/master/src/formator.py) that there's a 1/4 drop of hard-coded total BRAM, FF and LUT after DDR is enabled, i.e., BRAM: 384->288, FF: 329280->245760, LUT: 164640->122800. DSP also dropped from 1344 to 1152, and URAM from 192 to 128.

**Comment by RipperJ** [comment]
Besides, [src/formator.py:161](https://github.com/Licheng-Guo/AutoBridge/blob/master/src/formator.py#L161) should be U280.SLR_AREA...?

**Comment by Licheng-Guo** [comment]
Hello @RipperJ, 

To obtain the area information, you need to draw a pblock and check the available resources of the pblock.

For your second question, the code under src/ has gone obsolete. Please check our new implementation under in-develop for the up-to-date code.

Thanks for your interest in our repo!

-Licheng

**Comment by RipperJ** [comment]
Got it, thanks!
