### ISSUE TITLE
`src/autobridge/Floorplan/__init__.py` breaks logging

### ISSUE THREAD

**Issue by Blaok** [Licheng-Guo/AutoBridge#18]
The current logging configuration in https://github.com/Licheng-Guo/AutoBridge/blob/master/src/autobridge/Floorplan/__init__.py breaks logging in two ways:

+ It makes the logging system print the logging message only, without any of the usual useful information like module name, line number, timestamp, etc.
+ It makes whoever imports autobridge crash when running from a directory without write permission

I can see that you are trying to keep a permanent log file. It'll be good if you could make it optional or default to somewhere like /tmp.

**Comment by Licheng-Guo** [comment]
fixed in 0.0.20220328.dev; dependency updated in tapa
