### ISSUE TITLE
[Error Report] Regression does not run

### ISSUE THREAD

**Issue by luojw-dwr** [Licheng-Guo/AutoBridge#7]
Hi,

I am running `regression/systolic_2x2/run.sh` with `Vivado HLS 2019.2/2020.1` and `Python 3.6.12`. When executing `step2-autobridge.py`, it reports:

```
Using Python-MIP package version 1.8.1
Traceback (most recent call last):
  File "./step2-autobridge.py", line 141, in <module>
    NaiveBalance = True)
  File "../../src/formator.py", line 167, in __init__
    self.safety_check()
  File "../../src/formator.py", line 172, in safety_check
    assert any('control_s_axi' in key for key in self.DDR_loc_2d_y.keys()), f'no constraint found for the control_s_axi'
AssertionError: no constraint found for the control_s_axi
```

Please contact if more concrete information is needed to debug. Thanks for your time.

**Comment by Licheng-Guo** [comment]
I forgot to push some updates, can you try the latest commit?

**Comment by luojw-dwr** [comment]
Hi there, the mentioned problem is perfectly fixed with the latest commit. Thanks a lot!
